# Generated by Django 3.2.4 on 2021-06-13 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name_plural": "Tags"},
        ),
    ]
