# Generated by Django 3.2.4 on 2021-06-19 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"permissions": (("can_edit", "Can edit Lesson info"),)},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"permissions": (("can_edit", "Can edit Student info"),)},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={
                "permissions": (("can_edit", "Can edit Tag info"),),
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"permissions": (("can_edit", "Can edit Teacher info"),)},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"permissions": (("can_edit", "Can edit Lesson Type info"),)},
        ),
    ]
