# Generated by Django 3.2.4 on 2021-06-19 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_auto_20210619_1441"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name_plural": "Tags"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={},
        ),
    ]
