# Generated by Django 3.2.4 on 2021-06-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_lesson_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_and_time',
            field=models.DateTimeField(blank=True, help_text='Date and time of the recording (autofilled from CRAIG/GIARC link)', null=True, unique=True),
        ),
    ]
