# Generated by Django 3.2.5 on 2021-07-03 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["name"]},
        ),
    ]
